### ISSUE TITLE
Several glTF 1.0 model can not be load

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#10]
I added Hilo3d to the test list of glTF 1.0 branch.
https://github.com/cx20/gltf-test/tree/1.0

However, Several glTF 1.0 model can not be load.
https://github.com/cx20/gltf-test/tree/1.0#gltf-11-tutorial-models
![image](https://user-images.githubusercontent.com/1833979/33124048-3889b772-cfbf-11e7-918c-dc047b76809a.png)

The following error is displayed on the console.
https://cdn.rawgit.com/cx20/gltf-test/81d767b44028ba1350bd3ec86788847711f73098/examples/Hilo3d/index.html?category=tutorialModels&model=TriangleWithoutIndices&scale=1&type=glTF
```js
index.js:67 
Uncaught (in promise) TypeError: Cannot read property 'node' of undefined
    at constructor.<anonymous> (index.js:67)
    at constructor.fire (Hilo3d.js:6)
    at constructor._loadNext (Hilo3d.js:11)
    at constructor._onItemError (Hilo3d.js:11)
    at Hilo3d.js:11
    at <anonymous>
```

**Comment by 06wj** [comment]
@cx20 the model need has ```scene``` property to identifie which of the scenes in the dictionary is to be displayed at load time.

**Comment by cx20** [comment]
Relate:
https://github.com/KhronosGroup/glTF/issues/815

**Comment by cx20** [comment]
Since the `scene` property is not mandatory, if it does not exist, I think that is correct to refer to the first element of scenes.
I am not familiar with the specifications well, so sorry if I made a mistake.

**Comment by 06wj** [comment]
In 1.0, the scenes is not an array.I think I can add a param in gltfLoader to support setting which scene to display.

**Comment by 06wj** [comment]
In v1.5.9, glTFLoader will use ```Object.keys[model.scenes][0]``` as the default scene.Also glTFLoader add ```defaultScene``` param  to set the default scene.

**Comment by cx20** [comment]
I updated the status of the glTF 1.0 branch of gltf-test.
https://github.com/cx20/gltf-test/tree/1.0#gltf-11-tutorial-models
![image](https://user-images.githubusercontent.com/1833979/33162486-0a7d10d2-d06d-11e7-9729-ddbc1da0f518.png)

Several models do not seem to be displayed correctly yet.
Do I need to modify the example code?

**Comment by 06wj** [comment]
@cx20  Now gltf 1.0 support is incomplete, follow-up will not be put into development. We mainly support the latest version.

**Comment by cx20** [comment]
I understood the current glTF 1.0 support status.
I will update gltf-test again when the library is updated.
