### ISSUE TITLE
How to use quaternions?

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#12]
Below is a sample of Quaternion using Three.js.
http://jsdo.it/cx20/qqSi

```js
function render() {

    // euler
    mesh1.rotation.x += Math.PI / 180;
    mesh1.rotation.y += Math.PI / 180;
    mesh1.rotation.z += Math.PI / 180;
    
    // quaternion
    var axis = new THREE.Vector3(1,1,1).normalize();
    angle += Math.PI / 180;
    var q = new THREE.Quaternion();
    q.setFromAxisAngle(axis,angle);
    mesh2.quaternion.copy(q);

    // render
    renderer.render( scene, camera );

}
```

How can I write code in Hilo3d to do the same?

I tried quaternion, but it seems that usage is wrong.
http://jsdo.it/cx20/cTNT
```js
    onUpdate: function() {
        var axis = new Hilo3d.Vector3(1,1,1);
        angle += Math.PI / 180;
        var q = new Hilo3d.Quaternion();
        q.setAxisAngle(axis, angle);
        this.quaternion.copy(q);
    }
```

**Comment by 06wj** [comment]
Sorry, Quaternion.setAxisAngle has a bug. v1.5.9 fixed it.  Here is the demo https://github.com/hiloteam/Hilo3d/blob/master/examples/geometry_box.html#L45

**Comment by 06wj** [comment]
``` var axis = new Hilo3d.Vector3(1,1,1);```
The axis should be normalize.

**Comment by cx20** [comment]
@06wj I was able to rotate using quaternion thanks to your advice.

http://jsdo.it/cx20/cTNT

```js
    onUpdate: function() {
        var axis = new Hilo3d.Vector3(1,1,1).normalize(); // add normalize()
        angle += Math.PI / 180;
        var q = new Hilo3d.Quaternion();
        q.setAxisAngle(axis, angle);  // elements are not necessary.
        this.quaternion.copy(q);
    }
```

**Comment by cx20** [comment]
This issue is closed as the problem is solved.

Next I will challenge the physical operation library.
https://qiita.com/cx20/items/3ebed669fb9c9e797935
