### ISSUE TITLE
How can I make a colored soccer ball?

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#13]
Is it possible to combine texture and color using BasicMaterial?

![image](https://user-images.githubusercontent.com/1833979/33177875-7d87c36c-d0a7-11e7-8c42-b4f2f096ba3a.png)

I could only make a solid color ball.
http://jsdo.it/cx20/iwHl

**Comment by 06wj** [comment]
Sorry, we do not support this feature yet.

**Comment by cx20** [comment]
@06wj I understood the current status. I would like to try it once the feature is support.

**Comment by 06wj** [comment]
@cx20 You can use PBRMaterial to combine texture and color.
```
new Hilo3d.PBRMaterial({
    baseColorMap:new Hilo3d.LazyTexture({
        src:'/assets/s/s/X/x/ssXxc.png' // football.png
    }),
    baseColor: new Hilo3d.Color(c[0], c[1], c[2]),
})
```

[demo](http://jsdo.it/06wj/eSYT)

**Comment by cx20** [comment]
@06wj excellent!
