### ISSUE TITLE
VertexColorTest.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#14]
I tried to display a new sample model VertexColorTest.gltf.
However, VertexColorTest.gltf is not displayed correctly.

https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=VertexColorTest&scale=1.0&type=glTF
![image](https://user-images.githubusercontent.com/1833979/34914455-795e2a4c-f956-11e7-943f-bf82cf80999b.png)

The correct result is as follows.
https://github.com/cx20/gltf-test/tree/master/tutorialModels/VertexColorTest
![image](https://user-images.githubusercontent.com/1833979/34914461-824367c6-f956-11e7-8950-a93d1ddaeded.png)

**Comment by 06wj** [comment]
Hi, v1.5.12 has fixed it.

**Comment by cx20** [comment]
I'm sorry. I confirmed that it has been fixed in the latest version.

![image](https://user-images.githubusercontent.com/1833979/34914783-eb8f0946-f95c-11e7-82cf-1a577729de87.png)
