### ISSUE TITLE
Hilo3d does not support scale of normal map?

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#20]
I tried to display models of some normal maps in Hilo3d.
However, Hilo3d does not seem to support scale of normal maps.

![image](https://user-images.githubusercontent.com/1833979/44419344-d66e0c00-a5b5-11e8-99aa-d0d47f432f82.png)

Hilo3d + Yunomi_normal_20.glb result:
http://jsdo.it/cx20/4MPF

Hilo3d + Material_07.gltf result:
http://jsdo.it/cx20/m6tR

**Comment by 06wj** [comment]
@cx20
 I updated the normalMap calculation method according to the [glTF spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#normaltextureinfoscale).  But the formula is not correct.
I make a PR to the spec.
https://github.com/KhronosGroup/glTF/pull/1429
