### ISSUE TITLE
Texture not updated if size is not power of 2

### ISSUE THREAD

**Issue by blahgeek** [hiloteam/Hilo3d#6]
For textures whose size is not power of 2, they would not be updated even if `needUpdate` or `autoUpdate` is set to true.

**Comment by steel1990** [comment]
Can you show your code with https://codepen.io/ or https://jsfiddle.net/

**Comment by blahgeek** [comment]
代码里将非2的N次方大小的texture resize后把this.image替换掉了，对于canvas或者video类型的texture来说，之后就无法更新了

**Comment by blahgeek** [comment]
After resizing textures whose size is not power of 2, `this.image` of Texture is replaced with the new image. For canvas and video textures, later updates would not be applied to renderer.

**Comment by steel1990** [comment]
This is a bug, we will fix it next version.
You can change the Texture's wrapS and wrapT to Hilo3d.constants.CLAMP_TO_EDGE, like this example: https://hiloteam.github.io/Hilo3d/examples/geometry_video.html
