### ISSUE TITLE
Cannon example doesn't descriptive enough

### ISSUE THREAD

**Issue by tynrare** [hiloteam/Hilo3d#6]
Hi.

I experienced few problems when tried to use [cannon by example](https://github.com/hiloteam/Hilo3d/blob/dev/examples/physics/cannon.html) and think it (example) should be extended:

1. Cannon and Hilo worlds works in different axes: Cannon uses Z as vertical, Hilo Y. It isn't issue itself since you can just set gravity in any direction, but for some bodies like [planes](http://schteppe.github.io/cannon.js/docs/classes/Plane.html) *it is* problem. All ground bodies has to be rotated:
```javascript
world.gravity.set(0, GRAVITY, 0); //Hilo's gravity direction
const groundBody = new cannon.Body({
		mass: 0, // mass == 0 makes the body static
		quaternion: new cannon.Quaternion(0, 0, 0).setFromEuler(-Math.PI / 2, 0, 0) //hilo's ground rotation
	});
```
Also i think it would be better to let cannon work in Z direction as it was, but then we need to swap axes like `hilomesh.setPosition(this.body.position.x, this.body.position.z, this.body.position.y); ` and rotation too.
2. [Line](https://github.com/hiloteam/Hilo3d/blob/dev/examples/physics/cannon.html#L40) `geometry = new Hilo3d.BoxGeometry( 2, 2, 2 );` incorrect because BoxGeometry works with object argument, `const geometry = new Hilo3d.BoxGeometry({ width: 2, height: 2, depth: 2 });`
3. It doesn't clear from example that Hilo's bodies (Boxes) has to be twice bigger than cannon's
```javascript
const geometry = new Hilo3d.BoxGeometry({ width: 2, height: 2, depth: 2 }); 
const shape = new cannon.Box(new cannon.Vec3(1, 1, 1)); //does it because cannon sets distance *from center*?
```
I don't sure is it problem exist only for boxes or whole cannon-hilo bind.

Thanks for your time!

**Comment by 06wj** [comment]
Hi.
I updated the cannon demo: https://raw.githack.com/hiloteam/Hilo3d/dev/examples/physics/cannon.html

About your questions:
1. It may be confusing to use two kinds of coordinates, I think it would  be better to use hilo coordinate system.
2. It is indeed incorrect, I fixed it.
3. The parameter of the cannon box is the halfExtents. See http://schteppe.github.io/cannon.js/docs/classes/Box.html

**Comment by tynrare** [comment]
@06wj thanks for response and your work. Nice example.

1. Yep, and i think we already use two coordinate systems. Again, default rotation just wrong in cannon if we use it with hilo. It doesn't critical, but at least it deserves some comment note in example
3. Yes, but still, "it doesn't clear" - i suggest add your comment about it in code

Please, check out this article - [The Importance of “Why” Docs](https://medium.com/better-programming/the-importance-of-why-docs-c8ffba0ea520). One line of comment can save hours of work for someone.
