### ISSUE TITLE
docs request: GeometryData.get() returns reference to same object without any warning

### ISSUE THREAD

**Issue by tynrare** [hiloteam/Hilo3d#7]
Spent couple hours trying to get correct normals. 
All was about data management:
```javascript
//Works like that
 points[0].position.copy(data.vertices.get(0));
 points[1].position.copy(data.vertices.get(1));
 points[2].position.copy(data.vertices.get(2));
//Doesn't work like that
const p0 = data.vertices.get(0);
const p1 = data.vertices.get(1);
const p2 = data.vertices.get(2);
//p0 === p1 === p2
points[0].position.copy(p0);
points[1].position.copy(p1);
points[2].position.copy(p2);
```
All because `get` returns reference to same vector object. Please, add warning about that in docs, and, optionally, additional method `getCopy` which should return vector copy

**Comment by tynrare** [comment]
P.S. The worst thing that
```javascript
const v = g.vertices.get(idx);
const n = g.normals.get(idx);
// v === n
```
returns same object. Took way to much time to understand

**Comment by 06wj** [comment]
https://hilo3d.js.org/docs/GeometryData.html#get

Update the doc and add getCopy in v1.14.0
