### ISSUE TITLE
How can I use vertex colors?

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#9]
I am trying to display basic primitives using various WebGL libraries.
https://qiita.com/cx20/items/0fa19c96aa6470d98807

I first tried a triangle. This seems to be no problem.
http://jsdo.it/cx20/gwMA

Next I tried a colored rectangle. However, I did not know how to set vertex color.
I would like to create a sample like the following, is it possible?
![image](https://user-images.githubusercontent.com/1833979/33024847-9200d98c-ce4f-11e7-87c3-bfcc6b268144.png)

**Comment by steel1990** [comment]
The vertex color is added in v1.5.8, and you can check the [demo](https://hiloteam.github.io/Hilo3d/examples/geometry_color.html).

**Comment by cx20** [comment]
@steel1990 Thank you for adding functionality.

I tried making a vertex color sample using ShaderMaterial. Is the usage correct?
http://jsdo.it/cx20/KID2

Next I would like to challenge a colored cube.
![image](https://user-images.githubusercontent.com/1833979/33072854-5e619976-cf04-11e7-98e3-bad61d69624c.png)

**Comment by 06wj** [comment]
@cx20   http://jsdo.it/06wj/m5wa

**Comment by cx20** [comment]
@06wj Thanks for the advice. I was able to make the code simple.

**Comment by cx20** [comment]
I am challenging a colored cube, but it does not work...
http://jsdo.it/cx20/g4kh

@06wj Can you check whether u_modelViewProjectionMatrix uniform variable usage is correct?

**Comment by 06wj** [comment]
@cx20 

```
var camera = new Hilo3d.PerspectiveCamera({
    aspect: innerWidth / innerHeight,
    far: 100,
    near: 0.1,
    z: 3
});
```
The camera is wrong.You can use this code.

**Comment by cx20** [comment]
@06wj Great! I was able to display the cube.

http://jsdo.it/cx20/g4kh
![image](https://user-images.githubusercontent.com/1833979/33075713-bbf7f414-cf0d-11e7-9daf-4861ede12c77.png)

Next challenge the cube with texture!

**Comment by 06wj** [comment]
@cx20 You can get texture code in this [demo](https://github.com/hiloteam/Hilo3d/blob/master/examples/shader_material.html#L31)

**Comment by cx20** [comment]
@06wj I made a sample with reference to demo. However, UV seems to be incorrect. How can I set it?

http://jsdo.it/cx20/8FfP
![image](https://user-images.githubusercontent.com/1833979/33076263-9b094990-cf0f-11e7-8274-4b4b62e252bb.png)

**Comment by cx20** [comment]
When using SphereGeometry instead of BoxGeometry the texture was displayed. Is it a problem of BoxGeometry?
![image](https://user-images.githubusercontent.com/1833979/33076811-2b198b20-cf11-11e7-8b9e-e68abe767cca.png)

**Comment by 06wj** [comment]
https://github.com/hiloteam/Hilo3d/blob/master/examples/geometry_box.html#L17

**Comment by 06wj** [comment]
Because different box uv is not same,sphere is

**Comment by cx20** [comment]
I was able to display the texture in the box. Thank!

http://jsdo.it/cx20/8FfP
![image](https://user-images.githubusercontent.com/1833979/33077192-7c98683a-cf12-11e7-9f83-256e41bbd62a.png)

I added a sample of Hilo 3d to the list below.
https://qiita.com/cx20/items/0fa19c96aa6470d98807
![image](https://user-images.githubusercontent.com/1833979/33077544-702e74f8-cf13-11e7-9baa-6b1264ff9314.png)

**Comment by cx20** [comment]
Because the problem was solved, I will close this Issue.

**Comment by cx20** [comment]
BTW, I set the tag of `Hilo3d` in the sample of jsdo.it.
In the future, if the number of samples increases, you can display the list with this tag.

http://jsdo.it/tag/Hilo3d
